version: "3.6"

networks:
    docker_test:
        external: true

services:
    asset-transfer-basic.org1.cpsc5207.ca:
        build: .
        container_name: asset-transfer-basic.org1.cpsc5207.ca
        hostname: asset-transfer-basic.org1.cpsc5207.ca
        volumes:
            - ./crypto:/crypto
        env_file:
            - chaincode1.env
        networks:
            docker_test:
        expose:
            - 9999

    asset-transfer-basic.org2.cpsc5207.ca:
        build: .
        container_name: asset-transfer-basic.org2.cpsc5207.ca
        hostname: asset-transfer-basic.org2.cpsc5207.ca
        volumes:
            - ./crypto:/crypto
        env_file:
            - chaincode2.env
        networks:
            docker_test:
        expose:
            - 9999
